version: '2'
services:
  web:
    build: .
    volumes:
      - .:/ghost
      - /node_modules
    environment:
      - VIRTUAL_HOST=www.jackwang.local
      - NODE_ENV=development
    command: npm start
    working_dir: /ghost
    expose:
      - 80
    ports:
      - 3000:80